version: "3.8"
services:
  db:
    image: postgres:14
    container_name: devpulse-postgres
    restart: always
    environment:
      POSTGRES_USER: devpulse_user
      POSTGRES_PASSWORD: devpulse_pass
      POSTGRES_DB: devpulse
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
